# Site settings
title: My Jekyll Blog
#email: your-email@domain.com
description: "Github PagesでJekyllを使ったブログを運用するためのテストです。Jekyllに関するネタを書き留めています。"
baseurl: "http://takezoe.github.io/blog"
url: "http://takezoe.github.io/blog"

# Build settings
#markdown: kramdown
#permalink: prettay

markdown: redcarpet
redcarpet:
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink",
                 "tables", "with_toc_data"]
