# Site settings
title: My Jekyll Blog
email: your-email@domain.com
description: "This blog is test of Jekyll on Github Pages."
baseurl: "http://takezoe.github.io/blog"
url: "http://takezoe.github.io/blog"

# Build settings
markdown: kramdown
permalink: pretty
