# Site settings
title: My Jekyll Blog
email: your-email@domain.com
description: "I'm a Scala programmer. Author of GitBucket, Amateras and FreeStyle Wiki, also committer of Scalatra, Apache Click and The Seasar Software Foundation. This blog is test of Jekyll on Github Pages."
baseurl: "http://takezoe.github.io/blog"
url: "http://takezoe.github.io/blog"

# Build settings
markdown: kramdown
permalink: pretty
